<?php
// /modules/ess/payslip.php
$emp = essGetEmployee($pdo);
$empId = $emp['id'];
?>

<style>
.ess-page-header { background:linear-gradient(135deg,#0e4c92,#4086e4); border-radius:24px; padding:32px 36px; margin-bottom:25px; color:white; position:relative; overflow:hidden; box-shadow:0 20px 40px rgba(14,76,146,0.2); }
.ess-page-header::before { content:''; position:absolute; width:240px; height:240px; background:rgba(255,255,255,0.08); border-radius:50%; top:-100px; right:-60px; }
.ess-page-header .hdr-left { display:flex; align-items:center; gap:18px; position:relative; z-index:1; }
.ess-page-header .hdr-icon { width:60px; height:60px; background:rgba(255,255,255,0.18); border:1.5px solid rgba(255,255,255,0.3); border-radius:18px; display:flex; align-items:center; justify-content:center; font-size:26px; }
.ess-page-header h1 { font-size:24px; font-weight:700; margin:0 0 4px; }
.ess-page-header p { font-size:13px; margin:0; opacity:0.85; }

.ess-panel { background:white; border-radius:22px; overflow:hidden; box-shadow:0 10px 30px rgba(0,0,0,0.05); border:1px solid #eef2f6; margin-bottom:22px; }
.ess-panel-head { padding:18px 24px; background:linear-gradient(135deg,#f8fafd 0%,#f1f5f9 100%); border-bottom:1px solid #eef2f6; display:flex; align-items:center; gap:14px; }
.ess-panel-head .ico { width:40px; height:40px; border-radius:12px; background:linear-gradient(135deg,#0e4c92,#4086e4); color:white; display:flex; align-items:center; justify-content:center; font-size:17px; box-shadow:0 6px 15px rgba(14,76,146,0.25); }
.ess-panel-head h3 { margin:0; font-size:15px; font-weight:700; color:#1e293b; }
.ess-panel-body { padding:24px; }

.ess-empty { text-align:center; padding:60px 30px; color:#94a3b8; }
.ess-empty .icon-wrap { width:80px; height:80px; margin:0 auto 20px; background:linear-gradient(135deg,#eef2ff,#e0e7ff); border-radius:24px; display:flex; align-items:center; justify-content:center; font-size:32px; color:#6366f1; }
.ess-empty h3 { font-size:18px; color:#1e293b; margin:0 0 8px; font-weight:700; }
.ess-empty p { font-size:13px; color:#64748b; margin:0; }
</style>

<div class="ess-page-header">
    <div class="hdr-left">
        <div class="hdr-icon"><i class="fas fa-file-invoice-dollar"></i></div>
        <div>
            <h1>My Payslips</h1>
            <p>View and download your payslip history</p>
        </div>
    </div>
</div>

<div class="ess-panel">
    <div class="ess-panel-head">
        <div class="ico"><i class="fas fa-list"></i></div>
        <h3>Payslip Records</h3>
    </div>
    <div class="ess-panel-body">
        <div class="ess-empty">
            <div class="icon-wrap"><i class="fas fa-file-invoice-dollar"></i></div>
            <h3>No payslips available</h3>
            <p>Your payslips will appear here once they are generated by HR. <br>Contact HR if you have any questions.</p>
        </div>
    </div>
</div>